# -*- coding: utf-8 -*-
"""Classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/daffamaul30/Naive-Bayes/blob/master/Classification.ipynb
"""

import seaborn as sn
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics

from google.colab import drive 
drive.mount('/content/gdrive')
dataset = pd.read_csv("gdrive/My Drive/Colab Notebooks/datasetClassification.csv")

dataset.head()

#skill_moves sbg label
label = dataset['skill_moves'].tolist()
dataset = dataset.drop(columns=['skill_moves'])
# print(dataset)

x_train, x_test, y_train, y_test = train_test_split(dataset, label, test_size=0.3, random_state = 0)
# print(x_train)
# print('panjang x_train : ',len(x_train))
# print('panjang y_train : ',len(y_train))
# print(y_train)

model = GaussianNB()
model.fit(x_train,y_train)

y_predict = model.predict(x_test)

# print(y_predict)
y_predict

print("Akurasi Model : ",metrics.accuracy_score(y_test,y_predict))